version: '3'
services:

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart:
      always

  todofront:
    image: todofrontend
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000
    restart:
      always

  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    restart:
      always